version: "1"
rules:
  - base: dev
    upstream: HDInnovations:master    # change `wei` to the owner of upstream repo
    mergeMethod: rebase
    conflictReviewers:
      - howardlau1999
      - gyakkun
label: "auto-pull"
